### ISSUE TITLE
Leaflet.markercluster events

### ISSUE THREAD

**Issue by sbstnplcn** [jperelli/vue2-leaflet-markercluster#25]
Hi !
Is it possible to use Leaflet.markercluster events (https://github.com/Leaflet/Leaflet.markercluster#events) like spiderfied or unspiderfied in component ? 
Try to add @spiderfied or @clusterspiderfied and nothing works.

Thanks

**Comment by jperelli** [comment]
It works for me, just like in the example at this line https://github.com/jperelli/vue2-leaflet-markercluster/blob/master/example.vue#L5 I tried using `@spiderfied="log('pepe')"` and defined in the components method `log: function() {console.log(arguments)}`

Try using the latest v3.0.0, maybe it helps you. Otherwise please create and share a reproducible example. Thanks!
